# Generated by Django 3.1.3 on 2020-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=2048)),
                ('short_url', models.CharField(max_length=32)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField()),
                ('visit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'urlrecords',
            },
        ),
    ]
