# Generated by Django 3.1.3 on 2020-11-22 16:21

from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='expire_time',
            field=models.DateTimeField(
                default=urlshortener.models.one_minute_later),
        ),
        migrations.AlterField(
            model_name='urlrecord',
            name='long_url',
            field=models.URLField(max_length=2048),
        ),
    ]
