# Generated by Django 3.1.3 on 2020-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20201123_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlrecord',
            old_name='last_modified',
            new_name='last_activity_time',
        ),
        migrations.RemoveField(
            model_name='urlrecord',
            name='expire_time',
        ),
    ]
